### ISSUE TITLE
Installs wrong driver

### ISSUE THREAD

**Issue by skyzyx** [jugglinmike/selenium-chromedriver#1]
This seems to install v2.8/32-bit when it should be installing v2.9/64-bit on my system.

You can grab the latest release version number from http://chromedriver.storage.googleapis.com/LATEST_RELEASE.

**Comment by jugglinmike** [comment]
Hi @skyzyx thanks for the report!

Your receiving a binary for the incorrect architecture is definitely a bug. It's surprising because it functions correctly on my 64-bit system. Could you share the output of this command:

$ uname -a

As for the version: wow are you quick--I released this library on Thursday and it looks like 2.9 was released on Friday! I'm still working on a mechanism for specifying the chromedriver version, but for now, it's going to remain hard-coded.

**Comment by skyzyx** [comment]
OS X Mavericks, 10.9.1.

``` sh
$ uname -a
Darwin server.local 13.1.0 Darwin Kernel Version 13.1.0: Thu Jan 16 19:40:37 PST 2014; root:xnu-2422.90.20~2/RELEASE_X86_64 x86_64
```

Right now, I'm fetching the driver with Bash, but I'm wanting to simplify my install code by leveraging existing packages. Here's how I'm handling the versioning in Bash (for Ubuntu).

``` sh
sudo wget http://chromedriver.storage.googleapis.com/$(curl http://chromedriver.storage.googleapis.com/LATEST_RELEASE)/chromedriver_linux64.zip && \
sudo unzip chromedriver_linux64.zip && \
sudo chmod +x chromedriver
```

**Comment by jugglinmike** [comment]
Ah, I see. The Chromedriver team only offers a 32-bit version for Mac OSX--that's why you see the 32 bit version being downloaded on Mavericks (despite running on a 64-bit architecture).

I imagine that the 64-bit Linux binary could work on your Mac, but I don't know if it's safe to make this assumption for all OSX users and all releases of the Chromedriver.

**Comment by jugglinmike** [comment]
I'm no longer able to provide support for this module, so [I have deprecated it](https://github.com/jugglinmike/selenium-chromedriver/commit/985816c137ce6d4ae16f4d6721c89ba2d6e2344f). Check out [the ChromeDriver project](https://www.npmjs.com/package/chromedriver) for equivalent functionality.
